name: flutter_demo
description: A new Flutter application.


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_swiper: ^1.0.6
  flutter:
    sdk: flutter
  ## dio: ^1.0.9
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #international
  intl: ^0.15.7

  # add flutter_ScreenUtil
  flutter_screenutil: ^0.4.2

  # image_picker
  image_picker: 0.5.0+9
  #image_picker: 0.4.10

  # image_manager
  photo_manager: 0.3.3

  #wechat login
  fluwx: ^0.6.1

  #shared_preferences
  shared_preferences: ^0.5.1+2

  #  path_provider
  path_provider: ^0.5.0+1

  # sqflite
  sqflite: ^1.1.3

  #http
  http: ^0.12.0+2


  ### 使用 svg
  flutter_svg: ^0.12.4

  ### 网络检查
  connectivity: ^0.4.2+2

  ### 网络请求
  dio: ^2.1.2


  ### event_bus,先不使用 event_bus，自己实现一个简单的测试
 # event_bus: ^1.1.0

  ### 类似 event_bus
  flutter_redux: ^0.5.3
  ### 链式管理
  rxdart: ^0.21.0



  ### 状态栏相关
  flutter_statusbar: ^0.0.1

  ### 权限
  permission_handler: ^3.0.0

  ### 缓存管理
  flutter_cache_manager: ^0.3.2

  ### 动画及加载器
  flutter_spinkit: "^3.1.0"




  ### 本地插件引用
  flutter_toast_plugin:
    path: local_plugins/flutter_toast_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
       - locale/i18n_en.json
       - locale/i18n_zh.json
       - images/sample.jpg
       - images/bg.jpg
       - images/avatar2.png
       - images/nav_close.png
       - images/publish_chat_box.png
       - images/publish_work_line.png
       - images/publish_work_sign.png
       - images/share_qq.png
       - images/share_wechat.png
       - images/id_card.png
       - images/icon_qq.png
       - images/icon_wechat.png
       - images/icon_wechat_moments.png
       - images/dialog_outline.png

       - assets/icon/icon_one.svg
       - assets/icon/icon_two.svg
       - assets/icon/icon_three.svg





  # To add assets to your application, add an assets section, like this:
   #assets:
    #- images/sample.jpg
   # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
